import { Submission, ConnectedPlatform } from '@/types/submission';

export const mockSubmissions: Submission[] = [
  {
    id: '1',
    songUrl: 'https://open.spotify.com/track/4cOdK2wGLETKBW3PvgPWqT',
    platform: 'spotify',
    artistName: 'Rick Astley',
    songTitle: 'Never Gonna Give You Up',
    submitterName: 'John D.',
    submitterEmail: 'john@example.com',
    message: 'This is an absolute classic! Would love to hear your thoughts.',
    isPriority: true,
    status: 'pending',
    createdAt: new Date(Date.now() - 1000 * 60 * 5),
    queuePosition: 1,
  },
  {
    id: '2',
    songUrl: 'https://open.spotify.com/track/3n3Ppam7vgaVa1iaRUc9Lp',
    platform: 'spotify',
    artistName: 'Mr. Sandman',
    songTitle: 'Bring Me a Dream',
    submitterName: 'Sarah M.',
    message: 'Curious what you think of this vibe!',
    isPriority: false,
    status: 'pending',
    createdAt: new Date(Date.now() - 1000 * 60 * 15),
    queuePosition: 2,
  },
  {
    id: '3',
    songUrl: 'https://music.apple.com/track/1234567890',
    platform: 'apple-music',
    artistName: 'New Artist',
    songTitle: 'Fresh Beats',
    submitterName: 'Mike T.',
    submitterEmail: 'mike@example.com',
    message: 'Up and coming artist, really unique sound!',
    isPriority: false,
    status: 'pending',
    createdAt: new Date(Date.now() - 1000 * 60 * 30),
    queuePosition: 3,
  },
  {
    id: '4',
    songUrl: 'https://open.spotify.com/track/0VjIjW4GlUZAMYd2vXMi3b',
    platform: 'spotify',
    artistName: 'The Weeknd',
    songTitle: 'Blinding Lights',
    submitterName: 'Alex K.',
    isPriority: true,
    status: 'reviewed',
    feedback: 'Absolute banger! The synths are incredible and the 80s vibe is perfectly executed.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60),
    queuePosition: 4,
  },
  {
    id: '5',
    songUrl: 'https://soundcloud.com/artist/track',
    platform: 'soundcloud',
    artistName: 'Underground Producer',
    songTitle: 'Late Night Vibes',
    submitterName: 'Chris B.',
    message: 'Something a bit different for you',
    isPriority: false,
    status: 'reviewing',
    createdAt: new Date(Date.now() - 1000 * 60 * 45),
    queuePosition: 5,
  },
];

export const mockConnectedPlatforms: ConnectedPlatform[] = [
  { name: 'twitch', username: 'streamername', connected: true },
  { name: 'youtube', username: 'YT Channel', connected: true },
  { name: 'tiktok', username: '', connected: false },
  { name: 'instagram', username: '@streamer', connected: true },
  { name: 'kick', username: '', connected: false },
];
